### ISSUE TITLE
error opening config button

### ISSUE THREAD

**Issue by minigwen** [Sentilix/ClassicHealingAssignments#2]
Date: 2022-06-26 18:21:13
ID: 1
Error occured in: Global
Count: 1
Message: [string "*:OnShow"] line 1:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: PlaySound()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [string "=[C]"]: Show()
   [string "@ClassicHealingAssignments\HealingAssignments.lua"]:873: CHA_OpenConfigurationDialogue()
   [string "@ClassicHealingAssignments\HealingAssignments.lua"]:1302: CHA_AnnouncementButtonOnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

**Comment by Sentilix** [comment]
I cannot make it fail.
What game version are you running? (Classic, TBC, Retail...)

**Comment by minigwen** [comment]
i play classic.
error occurs 1st time i click on cha button, then no more until next reload / login

**Comment by Sentilix** [comment]
Hi,

I have still not been able to reproduce the bug, but I think I found the issue and fixed it in the just released version 2.0.1.

Thanks for the report.
